(function(){
    app.directive("searchBox",function(){
        return{
            templateUrl:"templates/searchBox.html",
            link:function(scope,elem,attrs){
                console.log(scope);
            }
        }
    });
})();